### ISSUE TITLE
This looks amazing, please add ability to configure for custom services

### ISSUE THREAD

**Issue by peterchoo** [rkstar/service-data-publisher#1]
As a package and a concept, I really like this.  There are bits of information that shouldn't be automatically published like they are, and this looks to do a great job of hiding that data.

In our organisation we have our own OAuth2 service, and again, we don't need all this information available to the client.  Instead of writing something ourselves to do this, would you be able to add the ability to pass in a config object registering a bespoke service, allowing us to say which fields/objects should be published (other than or overriding the default set)?

**Comment by rkstar** [comment]
sounds like a good idea.  what would you like this config object to look like?

**Comment by rkstar** [comment]
@peterchoo i've updated to `2.1.2` which now allows you to add your own services in whatever configuration you would like.  you can also overwrite the default configurations for buffer, facebook, google+, linkedin, and twitter simply by adding a config for them.
